version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    command: bash -c "/app/start.sh"
    env_file: .env
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=mydatabase
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
