apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # "mongoadmin" in Base64
  mongo-root-password: cGFzc3dvcmQxMjM=  # "password123" in Base64
